platform :ios, '12.0'
use_frameworks!
source "https://github.com/CocoaPods/Specs.git"
inhibit_all_warnings!

target 'CRBoostSwift_Example' do
  pod 'CRBoostSwift', :path => '../'
#  pod 'DoraemonKit', '~> 1.2.0', :subspecs => ['Core'], :configurations => ['Debug']
#  pod 'SwiftLint'

end
