platform :ios, '9'
use_frameworks!

target 'CRBoostSwift_Example' do
  pod 'CRBoostSwift', :path => '../'
#  pod 'DoraemonKit', '~> 1.2.0', :subspecs => ['Core'], :configurations => ['Debug']
#  pod 'SwiftLint'

end
